# Generated by Django 4.0.6 on 2022-08-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluedit', '0006_subbluedit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='subbluedit',
            name='description',
            field=models.CharField(max_length=128),
        ),
    ]
