# Generated by Django 4.0.6 on 2022-09-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluedit', '0008_subbluedit_member_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subbluedit',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
