# Generated by Django 4.0.6 on 2022-08-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluedit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(default='0'),
        ),
    ]
