# Generated by Django 4.0.6 on 2022-08-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluedit', '0004_alter_post_description_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
