# Generated by Django 4.0.6 on 2022-08-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluedit', '0005_alter_post_description_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbluedit',
            name='description',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
