# Generated by Django 4.0.6 on 2022-08-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluedit', '0007_alter_comment_text_alter_post_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbluedit',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
    ]
